### PR TITLE
Improvements in the code and structure of the directory

### PR DESCRIPTION
**Pull request by ignabelitzky**
This is some of the changes I made:
- .gitignore added
- Makefile created for easy compilation
- Deletition of unnecessary code
- Better names for the header file (without spaces)
- Elimination of "using namespace std" (this is a bad practice)
- Better structure for the directories (src and include directories created for source and header files)
- Rename of the functions in camel case
- Elimination of brackets in switch statement

Hope you can approve the Pull Request

### CODE REVIEW

**Comment by MAVUNDL** [comment]
Wonderful buddy. Pull request approved

**Comment by ignabelitzky** [comment]
> Wonderful buddy. Pull request approved

You are welcome!!
Consider to follow me if you like C++ programming... I have some interesting projects

**Comment by MAVUNDL** [comment]
Consider it done. Feel free to check out my other C++ programming projects and Improve the code, I would appreciate learning from you.

**Comment by ignabelitzky** [comment]
> Consider it done. Feel free to check out my other C++ programming projects and Improve the code, I would appreciate learning from you.

I would recommend you to checkout the library nCurses for C++ if you do cool things with the terminal...
for example this is a hangman game I made with that library:
https://youtu.be/0iGXgV4xUx4

Hope you like it!!!

**Pull request merged**
